title: "Quantum Machine Learning"
description: "Exploring the Future of AI with Quantum Computing"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # Options: air, dark, neon, etc.

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Navigation Tabs
nav:
  - title: "Home"
    url: /
  - title: "Background"
    url: /background/
  - title: "Tools & Techniques"
    url: /tools/
  - title: "Goals"
    url: /goals/
sass:
  load_paths:
    - _sass
    - assets/css
navigation: main
minimal_mistakes_skin: "mint"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      css: "/assets/css/custom.css"


markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax

  include:
  - assets/css

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      css: "/assets/css/custom.css"

